<?php
if(!defined('ABSPATH')){exit;}
final class NVConsult_Core_CRM{
 public static function init():void{add_action('init',[self::class,'register']);add_action('add_meta_boxes_nv_contact',[self::class,'box']);add_action('save_post_nv_contact',[self::class,'save'],20,2);add_filter('manage_nv_contact_posts_columns',[self::class,'columns']);add_action('manage_nv_contact_posts_custom_column',[self::class,'column'],10,2);}
 public static function register():void{register_post_type('nv_contact',['labels'=>['name'=>__('CRM Contacts','nvconsult-core'),'singular_name'=>__('CRM Contact','nvconsult-core'),'add_new_item'=>__('Add Contact / Lead','nvconsult-core')],'public'=>false,'show_ui'=>true,'show_in_menu'=>'edit.php?post_type=nv_application','supports'=>['title'],'capability_type'=>'post','map_meta_cap'=>true]);}
 public static function box():void{add_meta_box('nvc-crm-profile',__('Contact / Lead Profile','nvconsult-core'),[self::class,'render'],'nv_contact','normal','high');}
 public static function render(WP_Post$p):void{wp_nonce_field('nvc_crm','nvc_crm_nonce');$fields=['email'=>'Email','phone'=>'Phone / WhatsApp','country'=>'Country','source'=>'Lead source','service'=>'Interested service','next_action'=>'Next action date'];foreach($fields as$k=>$l){$v=(string)get_post_meta($p->ID,'_nvconsult_'.$k,true);printf('<p><label><strong>%s</strong></label><br><input %s name="nvc_%s" value="%s" style="width:100%%"></p>',esc_html__($l,'nvconsult-core'),$k==='next_action'?'type="date"':'type="text"',esc_attr($k),esc_attr($v));}$stage=(string)get_post_meta($p->ID,'_nvconsult_lead_stage',true)?:'new';echo'<p><label><strong>'.esc_html__('Pipeline stage','nvconsult-core').'</strong></label><br><select name="nvc_lead_stage" style="width:100%">';foreach(['new'=>'New','contacted'=>'Contacted','qualified'=>'Qualified','consultation'=>'Consultation','application'=>'Application','won'=>'Won','lost'=>'Lost']as$v=>$l)printf('<option value="%s" %s>%s</option>',esc_attr($v),selected($stage,$v,false),esc_html($l));echo'</select></p><p><label><strong>'.esc_html__('Internal CRM notes','nvconsult-core').'</strong></label><br><textarea name="nvc_crm_notes" rows="5" style="width:100%">'.esc_textarea((string)get_post_meta($p->ID,'_nvconsult_crm_notes',true)).'</textarea></p>';}
 public static function save(int$id,WP_Post$p):void{if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(!current_user_can('nvconsult_manage_applications'))return;if(!isset($_POST['nvc_crm_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nvc_crm_nonce'])),'nvc_crm'))return;foreach(['email','phone','country','source','service','next_action']as$k)update_post_meta($id,'_nvconsult_'.$k,sanitize_text_field(wp_unslash($_POST['nvc_'.$k]??'')));update_post_meta($id,'_nvconsult_crm_notes',sanitize_textarea_field(wp_unslash($_POST['nvc_crm_notes']??'')));$stage=sanitize_key($_POST['nvc_lead_stage']??'new');if(!in_array($stage,['new','contacted','qualified','consultation','application','won','lost'],true))$stage='new';update_post_meta($id,'_nvconsult_lead_stage',$stage);}
 public static function columns(array$c):array{$c['nvc_stage']=__('Stage','nvconsult-core');$c['nvc_service']=__('Service','nvconsult-core');$c['nvc_country']=__('Country','nvconsult-core');$c['nvc_next']=__('Next action','nvconsult-core');return$c;}
 public static function column(string$c,int$id):void{if($c==='nvc_stage')echo esc_html(ucfirst((string)get_post_meta($id,'_nvconsult_lead_stage',true)));elseif($c==='nvc_service')echo esc_html((string)get_post_meta($id,'_nvconsult_service',true));elseif($c==='nvc_country')echo esc_html((string)get_post_meta($id,'_nvconsult_country',true));elseif($c==='nvc_next')echo esc_html((string)get_post_meta($id,'_nvconsult_next_action',true));}
}
