<?php
if (!defined('ABSPATH')) { exit; }
final class NVConsult_Core_Applications {
 private const STATUS=['new','reviewing','documents','submitted','approved','rejected','closed'];
 private const TYPES=['job','program','scholarship','internship','consultation','general'];
 public static function init():void{add_action('init',[self::class,'register']);add_action('rest_api_init',[self::class,'routes']);add_action('add_meta_boxes_nv_application',[self::class,'add_box']);add_action('save_post_nv_application',[self::class,'save_admin'],10,2);}
 public static function register():void{register_post_type('nv_application',['labels'=>['name'=>__('Applications','nvconsult-core'),'singular_name'=>__('Application','nvconsult-core')],'public'=>false,'show_ui'=>true,'show_in_menu'=>true,'show_in_rest'=>false,'supports'=>['title'],'menu_icon'=>'dashicons-clipboard','capability_type'=>'post','map_meta_cap'=>true]);foreach(['_nvconsult_applicant_name','_nvconsult_email','_nvconsult_phone','_nvconsult_application_type','_nvconsult_status']as$key)register_post_meta('nv_application',$key,['type'=>'string','single'=>true,'show_in_rest'=>false,'sanitize_callback'=>'sanitize_text_field','auth_callback'=>static fn()=>current_user_can('nvconsult_manage_applications')]);foreach(['_nvconsult_target_id','_nvconsult_assigned_user_id','_nvconsult_user_id']as$key)register_post_meta('nv_application',$key,['type'=>'integer','single'=>true,'show_in_rest'=>false,'sanitize_callback'=>'absint','auth_callback'=>static fn()=>current_user_can('nvconsult_manage_applications')]);}
 public static function routes():void{register_rest_route('nvconsult/v1','/applications',['methods'=>WP_REST_Server::CREATABLE,'callback'=>[self::class,'create'],'permission_callback'=>'__return_true']);register_rest_route('nvconsult/v1','/applications/(?P<id>\d+)',['methods'=>WP_REST_Server::READABLE,'callback'=>[self::class,'view'],'permission_callback'=>[self::class,'can_view']]);}
 public static function create(WP_REST_Request$r){$name=sanitize_text_field((string)$r['name']);$email=sanitize_email((string)$r['email']);if($name===''||mb_strlen($name)>150||!is_email($email))return new WP_Error('invalid_application',__('Name and a valid email are required.','nvconsult-core'),['status'=>400]);$type=sanitize_key((string)$r['type']);if(!in_array($type,self::TYPES,true))$type='general';$target=absint($r['target_id']);if($target&&!self::valid_target($type,$target))return new WP_Error('invalid_target',__('The selected opportunity is not valid for this application type.','nvconsult-core'),['status'=>400]);$id=wp_insert_post(['post_type'=>'nv_application','post_status'=>'private','post_title'=>sprintf('%s — %s',$name,current_time('Y-m-d H:i'))],true);if(is_wp_error($id))return$id;update_post_meta($id,'_nvconsult_applicant_name',$name);update_post_meta($id,'_nvconsult_email',$email);update_post_meta($id,'_nvconsult_phone',substr(sanitize_text_field((string)$r['phone']),0,50));update_post_meta($id,'_nvconsult_application_type',$type);if($target)update_post_meta($id,'_nvconsult_target_id',$target);update_post_meta($id,'_nvconsult_status','new');if(is_user_logged_in())update_post_meta($id,'_nvconsult_user_id',get_current_user_id());$token=wp_generate_password(48,false,false);update_post_meta($id,'_nvconsult_tracking_hash',wp_hash_password($token));self::history($id,'created','new');return new WP_REST_Response(['application_id'=>$id,'status'=>'new','tracking_token'=>$token],201);}
 private static function valid_target(string$type,int$id):bool{$map=['job'=>'nv_job','program'=>'nv_program','scholarship'=>'nv_scholarship','internship'=>'nv_internship'];if(!isset($map[$type]))return$type==='general'||$type==='consultation';return get_post_type($id)===$map[$type]&&get_post_status($id)==='publish';}
 public static function can_view(WP_REST_Request$r):bool{if(current_user_can('nvconsult_manage_applications'))return true;$id=absint($r['id']);if(!$id||get_post_type($id)!=='nv_application')return false;if(is_user_logged_in()&&absint(get_post_meta($id,'_nvconsult_user_id',true))===get_current_user_id())return true;$token=sanitize_text_field((string)$r->get_param('token'));$hash=(string)get_post_meta($id,'_nvconsult_tracking_hash',true);return$token!==''&&$hash!==''&&wp_check_password($token,$hash);}
 public static function view(WP_REST_Request$r):WP_REST_Response{$id=absint($r['id']);return new WP_REST_Response(['id'=>$id,'type'=>(string)get_post_meta($id,'_nvconsult_application_type',true),'target_id'=>absint(get_post_meta($id,'_nvconsult_target_id',true)),'status'=>(string)get_post_meta($id,'_nvconsult_status',true),'updated'=>get_post_modified_time(DATE_ATOM,true,$id)],200);}
 public static function add_box():void{add_meta_box('nvconsult-application-status',__('Application Workflow','nvconsult-core'),[self::class,'render_box'],'nv_application','side','high');add_meta_box('nvconsult-application-history',__('Application History','nvconsult-core'),[self::class,'render_history'],'nv_application','normal','default');}
 public static function render_box(WP_Post$post):void{wp_nonce_field('nvconsult_application_admin','nvconsult_application_nonce');$current=(string)get_post_meta($post->ID,'_nvconsult_status',true);$assigned=absint(get_post_meta($post->ID,'_nvconsult_assigned_user_id',true));echo'<p><label><strong>'.esc_html__('Status','nvconsult-core').'</strong></label><br><select name="nvconsult_application_status" style="width:100%">';foreach(self::STATUS as$s)printf('<option value="%1$s" %2$s>%3$s</option>',esc_attr($s),selected($current,$s,false),esc_html(ucwords(str_replace('_',' ',$s))));echo'</select></p><p><label><strong>'.esc_html__('Assigned consultant','nvconsult-core').'</strong></label><br>';wp_dropdown_users(['name'=>'nvconsult_assigned_user_id','selected'=>$assigned,'show_option_none'=>__('Unassigned','nvconsult-core'),'role__in'=>['administrator','nvconsult_consultant']]);echo'</p>';}
 public static function render_history(WP_Post$post):void{$items=get_post_meta($post->ID,'_nvconsult_history',false);if(!$items){echo'<p>'.esc_html__('No history yet.','nvconsult-core').'</p>';return;}echo'<ul>';foreach(array_reverse($items)as$item)printf('<li><strong>%s</strong> — %s%s</li>',esc_html($item['time']??''),esc_html($item['message']??''),!empty($item['user'])?' <em>('.esc_html($item['user']).')</em>':'');echo'</ul>';}
 public static function save_admin(int$id,WP_Post$post):void{if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(!current_user_can('nvconsult_manage_applications'))return;if(!isset($_POST['nvconsult_application_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nvconsult_application_nonce'])),'nvconsult_application_admin'))return;$old=(string)get_post_meta($id,'_nvconsult_status',true);$new=sanitize_key($_POST['nvconsult_application_status']??'');if(in_array($new,self::STATUS,true)&&$new!==$old){update_post_meta($id,'_nvconsult_status',$new);self::history($id,'status',$new);self::notify_status($id,$new);}$old_assigned=absint(get_post_meta($id,'_nvconsult_assigned_user_id',true));$assigned=absint($_POST['nvconsult_assigned_user_id']??0);if($assigned&&!user_can($assigned,'nvconsult_manage_applications'))$assigned=0;if($assigned!==$old_assigned){if($assigned)update_post_meta($id,'_nvconsult_assigned_user_id',$assigned);else delete_post_meta($id,'_nvconsult_assigned_user_id');$u=$assigned?get_userdata($assigned):false;self::history($id,'assignment',$u?$u->display_name:__('Unassigned','nvconsult-core'));}}
 private static function history(int$id,string$type,string$value):void{$user=wp_get_current_user();$messages=['created'=>sprintf(__('Application created with status %s','nvconsult-core'),$value),'status'=>sprintf(__('Status changed to %s','nvconsult-core'),ucwords(str_replace('_',' ',$value))),'assignment'=>sprintf(__('Assigned consultant: %s','nvconsult-core'),$value),'note'=>$value];add_post_meta($id,'_nvconsult_history',['time'=>current_time('mysql'),'type'=>$type,'message'=>$messages[$type]??$value,'user'=>$user->exists()?$user->display_name:'System','user_id'=>$user->exists()?$user->ID:0]);}
 private static function notify_status(int$id,string$status):void{$email=sanitize_email((string)get_post_meta($id,'_nvconsult_email',true));if(!$email)return;wp_mail($email,__('NVConsult application status update','nvconsult-core'),sprintf(__('Your application #%1$d is now marked as %2$s. Sign in to your NVConsult portal to review the latest information.','nvconsult-core'),$id,ucwords(str_replace('_',' ',$status))));}
}
