<?php
if(!defined('ABSPATH')){exit;}
final class NVConsult_Core_Activity{
 public static function init():void{add_action('rest_api_init',[self::class,'routes']);add_action('add_meta_boxes_nv_application',[self::class,'box']);}
 public static function routes():void{register_rest_route('nvconsult/v1','/applications/(?P<id>\d+)/activity',['methods'=>WP_REST_Server::READABLE,'callback'=>[self::class,'feed'],'permission_callback'=>['NVConsult_Core_Messages','can_access']]);}
 public static function feed(WP_REST_Request$r):WP_REST_Response{return new WP_REST_Response(['items'=>self::items(absint($r['id']),current_user_can('nvconsult_manage_applications'))],200);}
 public static function box():void{add_meta_box('nvconsult-activity',__('Activity Feed','nvconsult-core'),[self::class,'render'],'nv_application','normal','default');}
 public static function render(WP_Post$p):void{$items=self::items($p->ID,true);if(!$items){echo'<p>'.esc_html__('No activity yet.','nvconsult-core').'</p>';return;}echo'<ul style="margin:0">';foreach(array_slice($items,0,75)as$i)printf('<li style="padding:8px 0;border-bottom:1px solid #eee"><strong>%s</strong> %s<br><small>%s%s</small></li>',esc_html(ucfirst($i['type'])),esc_html($i['text']),esc_html($i['time']),!empty($i['actor'])?' · '.esc_html($i['actor']):'');echo'</ul>';}
 public static function items(int$id,bool$staff=false):array{$out=[];$history=get_post_meta($id,'_nvconsult_history',false);foreach($history as$h){if(!$staff&&($h['type']??'')==='note')continue;$out[]=['type'=>'application','text'=>(string)($h['message']??''),'time'=>(string)($h['time']??''),'actor'=>'','ts'=>strtotime((string)($h['time']??''))?:0];}$followups=(array)get_post_meta($id,'_nvconsult_followup_history',true);foreach($followups as$h){$action=(string)($h['action']??'');$next=(string)($h['next']??'');$old=(string)($h['previous']??'');$uid=absint($h['user_id']??0);$u=$uid?get_userdata($uid):false;if($action==='complete')$text=$next?sprintf(__('Follow-up completed; next follow-up set for %s','nvconsult-core'),$next):__('Follow-up completed','nvconsult-core');else $text=sprintf(__('Follow-up snoozed from %1$s to %2$s','nvconsult-core'),$old?:'—',$next?:'—');$out[]=['type'=>'follow-up','text'=>$text,'time'=>(string)($h['time']??''),'actor'=>$u?$u->display_name:'','ts'=>strtotime((string)($h['time']??''))?:0];}$docs=get_posts(['post_type'=>'nv_document','post_status'=>'private','numberposts'=>-1,'meta_key'=>'_nvconsult_application_id','meta_value'=>$id]);foreach($docs as$d){$name=(string)get_post_meta($d->ID,'_nvconsult_original_name',true);$status=(string)get_post_meta($d->ID,'_nvconsult_document_status',true);$out[]=['type'=>'document','text'=>sprintf(__('%1$s — %2$s','nvconsult-core'),$name,ucwords(str_replace('_',' ',$status))),'time'=>get_post_modified_time('Y-m-d H:i',false,$d),'actor'=>'','ts'=>get_post_modified_time('U',true,$d)];}$msgs=get_posts(['post_type'=>'nv_message','post_status'=>'private','numberposts'=>100,'meta_key'=>'_nvconsult_application_id','meta_value'=>$id]);foreach($msgs as$m){$role=(string)get_post_meta($m->ID,'_nvconsult_sender_role',true);$out[]=['type'=>'message','text'=>sprintf(__('%s sent a message','nvconsult-core'),$role==='staff'?__('NVConsult','nvconsult-core'):__('Applicant','nvconsult-core')),'time'=>get_post_time('Y-m-d H:i',false,$m),'actor'=>'','ts'=>get_post_time('U',true,$m)];}usort($out,static fn($a,$b)=>$b['ts']<=>$a['ts']);return$out;}
}
