<?php
if(!defined('ABSPATH')){exit;}
final class NVConsult_Core_Staff_Collaboration{
 public static function init():void{add_action('add_meta_boxes_nv_application',[self::class,'boxes']);add_action('save_post_nv_application',[self::class,'save'],50,2);}
 public static function boxes():void{add_meta_box('nvc-internal-note',__('Internal Collaboration','nvconsult-core'),[self::class,'render'],'nv_application','normal','high');}
 public static function render(WP_Post$p):void{wp_nonce_field('nvc_collaboration','nvc_collaboration_nonce');$notes=(array)get_post_meta($p->ID,'_nvconsult_internal_notes',true);echo'<p><strong>'.esc_html__('Private staff note','nvconsult-core').'</strong></p><textarea name="nvc_internal_note" rows="4" style="width:100%" placeholder="'.esc_attr__('Visible to authorized NVConsult staff only. Use @Name when handing off or flagging a colleague.','nvconsult-core').'"></textarea><p><strong>'.esc_html__('Reassignment reason','nvconsult-core').'</strong></p><input type="text" name="nvc_handoff_reason" style="width:100%" placeholder="'.esc_attr__('Reason for consultant hand-off, if ownership changed','nvconsult-core').'">';if($notes){echo'<h4>'.esc_html__('Recent internal notes','nvconsult-core').'</h4><ul>';foreach(array_reverse(array_slice($notes,-10))as$n){$u=get_userdata(absint($n['user_id']??0));printf('<li style="padding:8px 0;border-bottom:1px solid #eee"><strong>%s</strong> <small>%s</small><br>%s</li>',esc_html($u?$u->display_name:__('Staff','nvconsult-core')),esc_html((string)($n['time']??'')),esc_html((string)($n['text']??'')));}echo'</ul>';}}
 public static function save(int$id,WP_Post$p):void{if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(!current_user_can('nvconsult_manage_applications'))return;if(!isset($_POST['nvc_collaboration_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nvc_collaboration_nonce'])),'nvc_collaboration'))return;$note=sanitize_textarea_field(wp_unslash($_POST['nvc_internal_note']??''));if($note){$notes=(array)get_post_meta($id,'_nvconsult_internal_notes',true);$notes[]=['text'=>$note,'user_id'=>get_current_user_id(),'time'=>current_time('mysql')];if(count($notes)>200)$notes=array_slice($notes,-200);update_post_meta($id,'_nvconsult_internal_notes',$notes);add_post_meta($id,'_nvconsult_history',['type'=>'note','message'=>$note,'time'=>current_time('mysql'),'user_id'=>get_current_user_id()]);self::mentions($id,$note);}$previous=absint(get_post_meta($id,'_nvconsult_last_owner_id',true));$current=absint(get_post_meta($id,'_nvconsult_assigned_user_id',true));if(!$previous&&$current){update_post_meta($id,'_nvconsult_last_owner_id',$current);self::ownership($id,0,$current,__('Initial assignment','nvconsult-core'));}elseif($previous!==$current){$reason=sanitize_text_field(wp_unslash($_POST['nvc_handoff_reason']??''));self::ownership($id,$previous,$current,$reason);update_post_meta($id,'_nvconsult_last_owner_id',$current);}}
 private static function ownership(int$id,int$from,int$to,string$reason):void{$history=(array)get_post_meta($id,'_nvconsult_ownership_history',true);$history[]=['from'=>$from,'to'=>$to,'reason'=>$reason,'changed_by'=>get_current_user_id(),'time'=>current_time('mysql')];if(count($history)>100)$history=array_slice($history,-100);update_post_meta($id,'_nvconsult_ownership_history',$history);$fu=$from?get_userdata($from):false;$tu=$to?get_userdata($to):false;$text=sprintf(__('Case ownership changed from %1$s to %2$s%3$s','nvconsult-core'),$fu?$fu->display_name:__('Unassigned','nvconsult-core'),$tu?$tu->display_name:__('Unassigned','nvconsult-core'),$reason?' — '.$reason:'');add_post_meta($id,'_nvconsult_history',['type'=>'ownership','message'=>$text,'time'=>current_time('mysql'),'user_id'=>get_current_user_id()]);if($tu&&$tu->user_email)wp_mail($tu->user_email,__('NVConsult case assigned to you','nvconsult-core'),sprintf(__('Application #%1$d has been assigned to you.%2$s','nvconsult-core'),$id,$reason?' Reason: '.$reason:''));}
 private static function mentions(int$id,string$text):void{if(!preg_match_all('/@([\p{L}\p{N}._-]+)/u',$text,$m))return;foreach(array_unique($m[1])as$token){$users=get_users(['search'=>'*'.$token.'*','search_columns'=>['user_login','display_name'],'number'=>5]);foreach($users as$u){if(!user_can($u,'nvconsult_manage_applications'))continue;wp_mail($u->user_email,__('NVConsult: you were mentioned','nvconsult-core'),sprintf(__('You were mentioned in an internal note on application #%d.','nvconsult-core'),$id));}}}
}
