<?php
if(!defined('ABSPATH')){exit;}
final class NVConsult_Core_Security{
 public static function init():void{add_filter('rest_pre_dispatch',[self::class,'rate_limit'],10,3);add_action('send_headers',[self::class,'security_headers']);add_filter('wp_privacy_personal_data_erasers',[self::class,'eraser']);}
 public static function security_headers():void{if(headers_sent())return;header('X-Content-Type-Options: nosniff');header('Referrer-Policy: strict-origin-when-cross-origin');header('Permissions-Policy: camera=(), microphone=(), geolocation=()');}
 public static function rate_limit($result,WP_REST_Server$server,WP_REST_Request$request){$route=$request->get_route();if(strpos($route,'/nvconsult/v1/')!==0)return$result;$uid=get_current_user_id();$ip=isset($_SERVER['REMOTE_ADDR'])?sanitize_text_field(wp_unslash($_SERVER['REMOTE_ADDR'])):'guest';$identity=$uid?'u:'.$uid:'ip:'.$ip;$is_public_create=!$uid&&$route==='/nvconsult/v1/applications'&&$request->get_method()==='POST';$bucket=$is_public_create?gmdate('YmdHi',time()-(time()%600)):gmdate('YmdHi');$key='nvc_rl_'.md5($identity.'|'.$route.'|'.$bucket);$n=(int)get_transient($key);$limit=$is_public_create?8:($uid?180:30);$ttl=$is_public_create?11*MINUTE_IN_SECONDS:2*MINUTE_IN_SECONDS;if($n>=$limit)return new WP_Error('nvc_rate_limit',__('Too many requests. Please retry later.','nvconsult-core'),['status'=>429]);set_transient($key,$n+1,$ttl);return$result;}
 public static function eraser(array$e):array{$e['nvconsult-core']=['eraser_friendly_name'=>__('NVConsult applicant data','nvconsult-core'),'callback'=>[self::class,'erase']];return$e;}
 public static function erase(string$email,int$page=1):array{$email=sanitize_email($email);$ids=[];$user=get_user_by('email',$email);if($user)$ids=array_merge($ids,get_posts(['post_type'=>'nv_application','post_status'=>'any','numberposts'=>100,'fields'=>'ids','meta_key'=>'_nvconsult_user_id','meta_value'=>$user->ID]));$ids=array_merge($ids,get_posts(['post_type'=>'nv_application','post_status'=>'any','numberposts'=>100,'fields'=>'ids','meta_key'=>'_nvconsult_email','meta_value'=>$email]));$ids=array_unique(array_map('absint',$ids));$removed=false;foreach($ids as$id){foreach(['_nvconsult_applicant_name','_nvconsult_email','_nvconsult_phone','_nvconsult_passport','_nvconsult_address','_nvconsult_tracking_hash']as$k)if(metadata_exists('post',$id,$k)){delete_post_meta($id,$k);$removed=true;}}return['items_removed'=>$removed,'items_retained'=>(bool)$ids,'messages'=>$ids?[__('Case records may be retained where legally or contractually required; supported direct identifiers and tracking credentials were removed.','nvconsult-core')]:[],'done'=>true];}
}
