<?php
if(!defined('ABSPATH')){exit;}
final class NVConsult_Core_Partner_CRM{
 public static function init():void{add_action('init',[self::class,'register']);add_action('add_meta_boxes_nv_partner',[self::class,'box']);add_action('save_post_nv_partner',[self::class,'save'],20,2);}
 public static function register():void{register_post_type('nv_partner',['labels'=>['name'=>__('Partners & Institutions','nvconsult-core'),'singular_name'=>__('Partner / Institution','nvconsult-core')],'public'=>false,'show_ui'=>true,'show_in_menu'=>'edit.php?post_type=nv_application','supports'=>['title'],'show_in_rest'=>true]);}
 public static function box():void{add_meta_box('nvc-partner-profile',__('Relationship Profile','nvconsult-core'),[self::class,'render'],'nv_partner','normal','high');}
 public static function render(WP_Post$p):void{wp_nonce_field('nvc_partner','nvc_partner_nonce');$type=(string)get_post_meta($p->ID,'_nvconsult_partner_type',true)?:'employer';echo'<p><strong>'.esc_html__('Type','nvconsult-core').'</strong><br><select name="nvc_partner_type">';foreach(['employer'=>'Employer','university'=>'University','college'=>'College','recruitment_agency'=>'Recruitment Agency','internship_host'=>'Internship Host','scholarship_provider'=>'Scholarship Provider','other'=>'Other']as$v=>$l)printf('<option value="%s" %s>%s</option>',esc_attr($v),selected($type,$v,false),esc_html($l));echo'</select></p>';foreach(['country'=>'Country','contact_name'=>'Contact person','contact_email'=>'Email','contact_phone'=>'Phone','website'=>'Website','agreement_status'=>'Agreement status','next_followup'=>'Next follow-up']as$k=>$l)printf('<p><strong>%s</strong><br><input %s name="nvc_%s" value="%s" style="width:100%%"></p>',esc_html__($l,'nvconsult-core'),$k==='next_followup'?'type="date"':'type="text"',esc_attr($k),esc_attr((string)get_post_meta($p->ID,'_nvconsult_'.$k,true)));echo'<p><strong>'.esc_html__('Relationship notes','nvconsult-core').'</strong><br><textarea name="nvc_partner_notes" rows="6" style="width:100%">'.esc_textarea((string)get_post_meta($p->ID,'_nvconsult_partner_notes',true)).'</textarea></p>';}
 public static function save(int$id,WP_Post$p):void{if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(!current_user_can('nvconsult_manage_applications'))return;if(!isset($_POST['nvc_partner_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nvc_partner_nonce'])),'nvc_partner'))return;foreach(['partner_type','country','contact_name','contact_email','contact_phone','website','agreement_status','next_followup']as$k)update_post_meta($id,'_nvconsult_'.$k,sanitize_text_field(wp_unslash($_POST['nvc_'.$k]??'')));update_post_meta($id,'_nvconsult_partner_notes',sanitize_textarea_field(wp_unslash($_POST['nvc_partner_notes']??'')));}
}
