<?php
if(!defined('ABSPATH')){exit;}
final class NVConsult_Core_Staff_Dashboard{
 public static function init():void{add_action('admin_menu',[self::class,'menu'],9);}
 public static function menu():void{if(current_user_can('nvconsult_manage_applications'))add_submenu_page('edit.php?post_type=nv_application',__('Operations Dashboard','nvconsult-core'),__('Operations Dashboard','nvconsult-core'),'nvconsult_manage_applications','nvconsult-operations',[self::class,'render']);}
 public static function render():void{if(!current_user_can('nvconsult_manage_applications'))wp_die(esc_html__('Access denied.','nvconsult-core'));$apps=get_posts(['post_type'=>'nv_application','post_status'=>'private','numberposts'=>-1]);$counts=[];$unassigned=0;foreach($apps as$a){$s=(string)get_post_meta($a->ID,'_nvconsult_status',true)?:'new';$counts[$s]=($counts[$s]??0)+1;if(!absint(get_post_meta($a->ID,'_nvconsult_assigned_user_id',true)))$unassigned++;}$pending=get_posts(['post_type'=>'nv_document','post_status'=>'private','numberposts'=>-1,'fields'=>'ids','meta_query'=>[['key'=>'_nvconsult_document_status','value'=>['uploaded','pending','pending_review'],'compare'=>'IN']]]);$unread=NVConsult_Core_Messages::unread_count();echo'<div class="wrap"><h1>'.esc_html__('NVConsult Operations Dashboard','nvconsult-core').'</h1><p>'.esc_html__('Daily workload and priority queues.','nvconsult-core').'</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:14px;max-width:1100px;margin:20px 0">';self::stat(__('Applications','nvconsult-core'),count($apps),'edit.php?post_type=nv_application');self::stat(__('Unassigned','nvconsult-core'),$unassigned,'edit.php?post_type=nv_application');self::stat(__('Pending documents','nvconsult-core'),count($pending),'edit.php?post_type=nv_document');self::stat(__('Unread messages','nvconsult-core'),$unread,'edit.php?post_type=nv_application&page=nvconsult-message-inbox');echo'</div><h2>'.esc_html__('Applications by status','nvconsult-core').'</h2><table class="widefat striped" style="max-width:760px"><tbody>';foreach(['new','reviewing','documents','submitted','approved','rejected','closed']as$s)printf('<tr><td>%s</td><td><strong>%d</strong></td></tr>',esc_html(ucwords(str_replace('_',' ',$s))),absint($counts[$s]??0));echo'</tbody></table>';self::consultants($apps);self::priority($apps);echo'</div>';}
 private static function stat(string$l,int$n,string$url):void{printf('<a href="%s" style="text-decoration:none;color:inherit;background:#fff;border:1px solid #ddd;border-radius:10px;padding:18px"><strong style="font-size:28px;display:block">%d</strong><span>%s</span></a>',esc_url(admin_url($url)),absint($n),esc_html($l));}
 private static function consultants(array$apps):void{$load=[];foreach($apps as$a){$uid=absint(get_post_meta($a->ID,'_nvconsult_assigned_user_id',true));if($uid)$load[$uid]=($load[$uid]??0)+1;}echo'<h2>'.esc_html__('Consultant workload','nvconsult-core').'</h2><table class="widefat striped" style="max-width:760px"><thead><tr><th>'.esc_html__('Consultant','nvconsult-core').'</th><th>'.esc_html__('Active cases','nvconsult-core').'</th></tr></thead><tbody>';if(!$load)echo'<tr><td colspan="2">'.esc_html__('No assigned cases.','nvconsult-core').'</td></tr>';arsort($load);foreach($load as$uid=>$n){$u=get_userdata($uid);if($u)printf('<tr><td>%s</td><td>%d</td></tr>',esc_html($u->display_name),absint($n));}echo'</tbody></table>';}
 private static function priority(array$apps):void{usort($apps,static fn($a,$b)=>get_post_modified_time('U',true,$a)<=>get_post_modified_time('U',true,$b));echo'<h2>'.esc_html__('Priority queue','nvconsult-core').'</h2><table class="widefat striped"><thead><tr><th>'.esc_html__('Application','nvconsult-core').'</th><th>'.esc_html__('Applicant','nvconsult-core').'</th><th>'.esc_html__('Status','nvconsult-core').'</th><th>'.esc_html__('Assigned','nvconsult-core').'</th><th>'.esc_html__('Last update','nvconsult-core').'</th></tr></thead><tbody>';foreach(array_slice($apps,0,20)as$a){$uid=absint(get_post_meta($a->ID,'_nvconsult_assigned_user_id',true));$u=$uid?get_userdata($uid):false;printf('<tr><td><a href="%s">#%d</a></td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>',esc_url(get_edit_post_link($a->ID)),$a->ID,esc_html((string)get_post_meta($a->ID,'_nvconsult_applicant_name',true)),esc_html(ucwords(str_replace('_',' ',(string)get_post_meta($a->ID,'_nvconsult_status',true)))),esc_html($u?$u->display_name:__('Unassigned','nvconsult-core')),esc_html(get_post_modified_time(get_option('date_format').' '.get_option('time_format'),false,$a)));}echo'</tbody></table>';}
}
