<?php
if(!defined('ABSPATH')){exit;}
final class NVConsult_Core_Messages{
 public static function init():void{add_action('init',[self::class,'register']);add_action('rest_api_init',[self::class,'routes']);add_action('admin_menu',[self::class,'admin_menu']);}
 public static function register():void{register_post_type('nv_message',['labels'=>['name'=>__('Messages','nvconsult-core'),'singular_name'=>__('Message','nvconsult-core')],'public'=>false,'show_ui'=>false,'show_in_rest'=>false,'supports'=>[]]);}
 public static function routes():void{register_rest_route('nvconsult/v1','/applications/(?P<id>\d+)/messages',[[ 'methods'=>WP_REST_Server::READABLE,'callback'=>[self::class,'list_messages'],'permission_callback'=>[self::class,'can_access']],[ 'methods'=>WP_REST_Server::CREATABLE,'callback'=>[self::class,'send'],'permission_callback'=>[self::class,'can_access']]]);}
 public static function can_access(WP_REST_Request$r):bool{$id=absint($r['id']);if(!$id||get_post_type($id)!=='nv_application')return false;if(current_user_can('nvconsult_manage_applications'))return true;return is_user_logged_in()&&absint(get_post_meta($id,'_nvconsult_user_id',true))===get_current_user_id();}
 public static function list_messages(WP_REST_Request$r):WP_REST_Response{$id=absint($r['id']);$staff=current_user_can('nvconsult_manage_applications');$messages=get_posts(['post_type'=>'nv_message','post_status'=>'private','numberposts'=>100,'orderby'=>'date','order'=>'ASC','meta_key'=>'_nvconsult_application_id','meta_value'=>$id]);$items=[];foreach($messages as$m){$role=(string)get_post_meta($m->ID,'_nvconsult_sender_role',true);$author=absint(get_post_meta($m->ID,'_nvconsult_sender_id',true));$u=$author?get_userdata($author):false;$items[]=['id'=>$m->ID,'body'=>(string)get_post_meta($m->ID,'_nvconsult_message_body',true),'sender'=>$u?$u->display_name:__('NVConsult','nvconsult-core'),'sender_role'=>$role,'created'=>get_post_time(DATE_ATOM,true,$m->ID)];if(($staff&&$role==='applicant')||(!$staff&&$role==='staff'))update_post_meta($m->ID,$staff?'_nvconsult_read_staff':'_nvconsult_read_applicant',current_time('mysql'));}return new WP_REST_Response(['items'=>$items],200);}
 public static function send(WP_REST_Request$r){$id=absint($r['id']);$body=sanitize_textarea_field((string)$r->get_param('message'));if($body==='')return new WP_Error('empty_message',__('Message cannot be empty.','nvconsult-core'),['status'=>400]);if(strlen($body)>5000)return new WP_Error('message_too_long',__('Message is too long.','nvconsult-core'),['status'=>400]);$staff=current_user_can('nvconsult_manage_applications');$mid=wp_insert_post(['post_type'=>'nv_message','post_status'=>'private','post_title'=>'Message — Application '.$id],true);if(is_wp_error($mid))return$mid;update_post_meta($mid,'_nvconsult_application_id',$id);update_post_meta($mid,'_nvconsult_sender_id',get_current_user_id());update_post_meta($mid,'_nvconsult_sender_role',$staff?'staff':'applicant');update_post_meta($mid,'_nvconsult_message_body',$body);delete_transient('nvc_unread_staff_messages');self::notify($id,$staff,$body);return new WP_REST_Response(['id'=>$mid,'created'=>get_post_time(DATE_ATOM,true,$mid)],201);}
 public static function admin_menu():void{if(current_user_can('nvconsult_manage_applications'))add_submenu_page('edit.php?post_type=nv_application',__('Message Inbox','nvconsult-core'),sprintf(__('Message Inbox %s','nvconsult-core'),self::unread_badge()),'nvconsult_manage_applications','nvconsult-message-inbox',[self::class,'inbox']);}
 private static function unread_badge():string{$n=self::unread_count();return$n?'<span class="awaiting-mod">'.absint($n).'</span>':'';}
 public static function unread_count():int{$cached=get_transient('nvc_unread_staff_messages');if($cached!==false)return(int)$cached;$q=new WP_Query(['post_type'=>'nv_message','post_status'=>'private','posts_per_page'=>1,'fields'=>'ids','no_found_rows'=>false,'meta_query'=>[['key'=>'_nvconsult_sender_role','value'=>'applicant'],['key'=>'_nvconsult_read_staff','compare'=>'NOT EXISTS']]]);$n=(int)$q->found_posts;set_transient('nvc_unread_staff_messages',$n,5*MINUTE_IN_SECONDS);return$n;}
 public static function inbox():void{if(!current_user_can('nvconsult_manage_applications'))wp_die(esc_html__('Access denied.','nvconsult-core'));$messages=get_posts(['post_type'=>'nv_message','post_status'=>'private','numberposts'=>100,'orderby'=>'date','order'=>'DESC','meta_key'=>'_nvconsult_sender_role','meta_value'=>'applicant']);echo'<div class="wrap"><h1>'.esc_html__('Applicant Message Inbox','nvconsult-core').'</h1><table class="widefat striped"><thead><tr><th>'.esc_html__('Applicant','nvconsult-core').'</th><th>'.esc_html__('Application','nvconsult-core').'</th><th>'.esc_html__('Message','nvconsult-core').'</th><th>'.esc_html__('Received','nvconsult-core').'</th></tr></thead><tbody>';foreach($messages as$m){$app=absint(get_post_meta($m->ID,'_nvconsult_application_id',true));$unread=!get_post_meta($m->ID,'_nvconsult_read_staff',true);printf('<tr%s><td>%s</td><td><a href="%s">#%d</a></td><td>%s</td><td>%s</td></tr>',$unread?' style="font-weight:600"':'',esc_html((string)get_post_meta($app,'_nvconsult_applicant_name',true)),esc_url(get_edit_post_link($app)),$app,esc_html(wp_trim_words((string)get_post_meta($m->ID,'_nvconsult_message_body',true),24,'…')),esc_html(get_post_time(get_option('date_format').' '.get_option('time_format'),false,$m)));}echo'</tbody></table></div>';}
 private static function notify(int$id,bool$staff,string$body):void{if($staff){$email=sanitize_email((string)get_post_meta($id,'_nvconsult_email',true));$subject=__('New message from NVConsult','nvconsult-core');}else{$assigned=absint(get_post_meta($id,'_nvconsult_assigned_user_id',true));$u=$assigned?get_userdata($assigned):false;$email=$u?$u->user_email:get_option('admin_email');$subject=__('New applicant message','nvconsult-core');}if(!$email)return;wp_mail($email,$subject,sprintf(__('Application #%1$d has a new message:\n\n%2$s','nvconsult-core'),$id,wp_trim_words($body,30,'…')));}
}
