<?php
if(!defined('ABSPATH')){exit;}
final class NVConsult_Core_Staff_Dashboard{
 public static function init():void{add_action('admin_menu',[self::class,'menu'],9);}
 public static function menu():void{if(current_user_can('nvconsult_manage_applications'))add_submenu_page('edit.php?post_type=nv_application',__('Operations Dashboard','nvconsult-core'),__('Operations Dashboard','nvconsult-core'),'nvconsult_manage_applications','nvconsult-operations',[self::class,'render']);}
 public static function render():void{if(!current_user_can('nvconsult_manage_applications'))wp_die(esc_html__('Access denied.','nvconsult-core'));$apps=get_posts(['post_type'=>'nv_application','post_status'=>'private','numberposts'=>-1]);$uid=get_current_user_id();$counts=[];$unassigned=0;$overdue=0;$my=[];$waiting=0;foreach($apps as$a){$s=(string)get_post_meta($a->ID,'_nvconsult_status',true)?:'new';$counts[$s]=($counts[$s]??0)+1;$assigned=absint(get_post_meta($a->ID,'_nvconsult_assigned_user_id',true));if(!$assigned)$unassigned++;if($assigned===$uid)$my[]=$a;$days=self::age($a);if(!in_array($s,['approved','rejected','closed'],true)&&$days>=7)$overdue++;foreach(NVConsult_Core_Document_Requests::items($a->ID)as$r)if($r['status']==='required'){$waiting++;break;}}$pending=get_posts(['post_type'=>'nv_document','post_status'=>'private','numberposts'=>-1,'fields'=>'ids','meta_query'=>[['key'=>'_nvconsult_document_status','value'=>['uploaded','pending','pending_review'],'compare'=>'IN']]]);$unread=NVConsult_Core_Messages::unread_count();echo'<div class="wrap"><h1>'.esc_html__('NVConsult Operations Dashboard','nvconsult-core').'</h1><p>'.esc_html__('Daily workload, aging and action queues.','nvconsult-core').'</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:14px;max-width:1200px;margin:20px 0">';self::stat(__('My cases','nvconsult-core'),count($my),'#nvc-my-cases');self::stat(__('Unassigned','nvconsult-core'),$unassigned,'edit.php?post_type=nv_application');self::stat(__('Overdue 7+ days','nvconsult-core'),$overdue,'#nvc-priority');self::stat(__('Waiting on applicant','nvconsult-core'),$waiting,'#nvc-priority');self::stat(__('Pending documents','nvconsult-core'),count($pending),'edit.php?post_type=nv_document');self::stat(__('Unread messages','nvconsult-core'),$unread,'edit.php?post_type=nv_application&page=nvconsult-message-inbox');echo'</div>';self::status_table($counts);self::case_table(__('My Cases','nvconsult-core'),$my,'nvc-my-cases',false);self::consultants($apps);self::case_table(__('Priority / SLA Queue','nvconsult-core'),$apps,'nvc-priority',true);echo'</div>';}
 private static function age(WP_Post$a):int{$ts=(int)get_post_modified_time('U',true,$a);return max(0,(int)floor((time()-$ts)/DAY_IN_SECONDS));}
 private static function stat(string$l,int$n,string$url):void{$href=str_starts_with($url,'#')?$url:admin_url($url);printf('<a href="%s" style="text-decoration:none;color:inherit;background:#fff;border:1px solid #ddd;border-radius:10px;padding:18px"><strong style="font-size:28px;display:block">%d</strong><span>%s</span></a>',esc_url($href),absint($n),esc_html($l));}
 private static function status_table(array$c):void{echo'<h2>'.esc_html__('Applications by status','nvconsult-core').'</h2><table class="widefat striped" style="max-width:760px"><tbody>';foreach(['new','reviewing','documents','submitted','approved','rejected','closed']as$s)printf('<tr><td>%s</td><td><strong>%d</strong></td></tr>',esc_html(ucwords(str_replace('_',' ',$s))),absint($c[$s]??0));echo'</tbody></table>';}
 private static function consultants(array$apps):void{$load=[];foreach($apps as$a){$s=(string)get_post_meta($a->ID,'_nvconsult_status',true);if(in_array($s,['approved','rejected','closed'],true))continue;$uid=absint(get_post_meta($a->ID,'_nvconsult_assigned_user_id',true));if($uid)$load[$uid]=($load[$uid]??0)+1;}echo'<h2>'.esc_html__('Consultant workload','nvconsult-core').'</h2><table class="widefat striped" style="max-width:760px"><thead><tr><th>'.esc_html__('Consultant','nvconsult-core').'</th><th>'.esc_html__('Active cases','nvconsult-core').'</th></tr></thead><tbody>';if(!$load)echo'<tr><td colspan="2">'.esc_html__('No assigned active cases.','nvconsult-core').'</td></tr>';arsort($load);foreach($load as$uid=>$n){$u=get_userdata($uid);if($u)printf('<tr><td>%s</td><td>%d</td></tr>',esc_html($u->display_name),absint($n));}echo'</tbody></table>';}
 private static function case_table(string$title,array$apps,string$id,bool$priority):void{if($priority)usort($apps,static fn($a,$b)=>self::score($b)<=>self::score($a));else usort($apps,static fn($a,$b)=>get_post_modified_time('U',true,$a)<=>get_post_modified_time('U',true,$b));echo'<h2 id="'.esc_attr($id).'">'.esc_html($title).'</h2><table class="widefat striped"><thead><tr><th>'.esc_html__('Application','nvconsult-core').'</th><th>'.esc_html__('Applicant','nvconsult-core').'</th><th>'.esc_html__('Status','nvconsult-core').'</th><th>'.esc_html__('Consultant','nvconsult-core').'</th><th>'.esc_html__('Age','nvconsult-core').'</th><th>'.esc_html__('Priority','nvconsult-core').'</th></tr></thead><tbody>';if(!$apps)echo'<tr><td colspan="6">'.esc_html__('No cases in this queue.','nvconsult-core').'</td></tr>';foreach(array_slice($apps,0,30)as$a){$s=(string)get_post_meta($a->ID,'_nvconsult_status',true);$uid=absint(get_post_meta($a->ID,'_nvconsult_assigned_user_id',true));$u=$uid?get_userdata($uid):false;$days=self::age($a);$flag=$days>=14?__('Critical','nvconsult-core'):($days>=7?__('Overdue','nvconsult-core'):($days>=3?__('Watch','nvconsult-core'):__('Normal','nvconsult-core')));printf('<tr><td><a href="%s">#%d</a></td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td><strong>%s</strong></td></tr>',esc_url(get_edit_post_link($a->ID)),$a->ID,esc_html((string)get_post_meta($a->ID,'_nvconsult_applicant_name',true)),esc_html(ucwords(str_replace('_',' ',$s))),esc_html($u?$u->display_name:__('Unassigned','nvconsult-core')),esc_html(sprintf(_n('%d day','%d days',$days,'nvconsult-core'),$days)),esc_html($flag));}echo'</tbody></table>';}
 private static function score(WP_Post$a):int{$s=(string)get_post_meta($a->ID,'_nvconsult_status',true);if(in_array($s,['approved','rejected','closed'],true))return-1000;$score=self::age($a);if(!absint(get_post_meta($a->ID,'_nvconsult_assigned_user_id',true)))$score+=10;foreach(NVConsult_Core_Document_Requests::items($a->ID)as$r)if($r['status']==='required'){$score+=4;break;}return$score;}
}
