<?php
if(!defined('ABSPATH')){exit;}
final class NVConsult_Core_Document_Requests{
 private const TYPES=['passport','cv','photo','academic','experience','language','financial','offer','visa','other'];
 public static function init():void{add_action('init',[self::class,'register']);add_action('rest_api_init',[self::class,'routes']);add_action('add_meta_boxes_nv_application',[self::class,'box']);add_action('save_post_nv_application',[self::class,'save'],30,2);add_action('save_post_nv_document',[self::class,'sync_for_document'],30,2);}
 public static function register():void{register_post_type('nv_doc_request',['public'=>false,'show_ui'=>false,'show_in_rest'=>false,'supports'=>[]]);}
 public static function routes():void{register_rest_route('nvconsult/v1','/applications/(?P<id>\d+)/document-requests',['methods'=>WP_REST_Server::READABLE,'callback'=>[self::class,'api'],'permission_callback'=>['NVConsult_Core_Messages','can_access']]);}
 public static function api(WP_REST_Request$r):WP_REST_Response{return new WP_REST_Response(['items'=>self::items(absint($r['id']))],200);}
 public static function box():void{add_meta_box('nvc-document-requests',__('Document Requests','nvconsult-core'),[self::class,'render'],'nv_application','normal','high');}
 public static function render(WP_Post$p):void{wp_nonce_field('nvc_doc_request','nvc_doc_request_nonce');$items=self::items($p->ID);echo'<table class="widefat striped"><thead><tr><th>'.esc_html__('Document','nvconsult-core').'</th><th>'.esc_html__('Request','nvconsult-core').'</th><th>'.esc_html__('Status','nvconsult-core').'</th></tr></thead><tbody>';if(!$items)echo'<tr><td colspan="3">'.esc_html__('No document requests.','nvconsult-core').'</td></tr>';foreach($items as$i)printf('<tr><td>%s</td><td>%s</td><td>%s</td></tr>',esc_html(ucfirst($i['type'])),esc_html($i['note']),esc_html(ucfirst($i['status'])));echo'</tbody></table><h4>'.esc_html__('Request another document','nvconsult-core').'</h4><p><select name="nvc_request_type"><option value="">'.esc_html__('Select document','nvconsult-core').'</option>';foreach(self::TYPES as$t)printf('<option value="%s">%s</option>',esc_attr($t),esc_html(ucfirst($t)));echo'</select></p><p><textarea name="nvc_request_note" rows="3" style="width:100%" placeholder="'.esc_attr__('Instructions for applicant','nvconsult-core').'"></textarea></p>';}
 public static function save(int$id,WP_Post$p):void{if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(!current_user_can('nvconsult_manage_applications'))return;if(!isset($_POST['nvc_doc_request_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nvc_doc_request_nonce'])),'nvc_doc_request'))return;$type=sanitize_key($_POST['nvc_request_type']??'');if(!in_array($type,self::TYPES,true))return;$note=sanitize_textarea_field(wp_unslash($_POST['nvc_request_note']??''));$rid=wp_insert_post(['post_type'=>'nv_doc_request','post_status'=>'private','post_title'=>ucfirst($type).' — Application '.$id],true);if(is_wp_error($rid))return;update_post_meta($rid,'_nvconsult_application_id',$id);update_post_meta($rid,'_nvconsult_request_type',$type);update_post_meta($rid,'_nvconsult_request_note',$note);update_post_meta($rid,'_nvconsult_request_status','required');$email=sanitize_email((string)get_post_meta($id,'_nvconsult_email',true));if($email)wp_mail($email,__('NVConsult: document required','nvconsult-core'),sprintf(__('A %1$s document is required for application #%2$d. %3$s Please sign in to your portal to upload it.','nvconsult-core'),$type,$id,$note));}
 public static function sync_for_document(int$id,WP_Post$p):void{if($p->post_type!=='nv_document'||wp_is_post_revision($id))return;$app=absint(get_post_meta($id,'_nvconsult_application_id',true));$type=(string)get_post_meta($id,'_nvconsult_document_type',true);if(!$app||!in_array($type,self::TYPES,true))return;$requests=get_posts(['post_type'=>'nv_doc_request','post_status'=>'private','numberposts'=>-1,'fields'=>'ids','meta_query'=>[['key'=>'_nvconsult_application_id','value'=>$app],['key'=>'_nvconsult_request_type','value'=>$type],['key'=>'_nvconsult_request_status','value'=>'required']]]);foreach($requests as$rid)update_post_meta($rid,'_nvconsult_request_status','uploaded');}
 public static function items(int$id):array{$requests=get_posts(['post_type'=>'nv_doc_request','post_status'=>'private','numberposts'=>100,'orderby'=>'date','order'=>'DESC','meta_key'=>'_nvconsult_application_id','meta_value'=>$id]);$out=[];foreach($requests as$r)$out[]=['id'=>$r->ID,'type'=>(string)get_post_meta($r->ID,'_nvconsult_request_type',true),'note'=>(string)get_post_meta($r->ID,'_nvconsult_request_note',true),'status'=>(string)get_post_meta($r->ID,'_nvconsult_request_status',true),'created'=>get_post_time(DATE_ATOM,true,$r)];return$out;}
}
