<?php
if(!defined('ABSPATH')){exit;}
final class NVConsult_Core_Notifications{
 public static function init():void{add_action('rest_api_init',[self::class,'routes']);}
 public static function routes():void{register_rest_route('nvconsult/v1','/notifications',[['methods'=>WP_REST_Server::READABLE,'callback'=>[self::class,'feed'],'permission_callback'=>static fn()=>is_user_logged_in()],['methods'=>WP_REST_Server::EDITABLE,'callback'=>[self::class,'mark_read'],'permission_callback'=>static fn()=>is_user_logged_in()]]);}
 public static function feed():WP_REST_Response{$uid=get_current_user_id();return new WP_REST_Response(['items'=>self::items($uid),'unread'=>self::unread_count($uid)],200);}
 public static function mark_read(WP_REST_Request$r):WP_REST_Response{$ids=array_map('sanitize_text_field',(array)$r->get_param('ids'));$seen=(array)get_user_meta(get_current_user_id(),'_nvconsult_seen_notifications',true);update_user_meta(get_current_user_id(),'_nvconsult_seen_notifications',array_values(array_unique(array_merge($seen,$ids))));return self::feed();}
 public static function unread_count(int$uid):int{$seen=(array)get_user_meta($uid,'_nvconsult_seen_notifications',true);$n=0;foreach(self::items($uid)as$i)if(!in_array($i['id'],$seen,true))$n++;return$n;}
 public static function items(int$uid):array{$apps=get_posts(['post_type'=>'nv_application','post_status'=>'private','numberposts'=>50,'fields'=>'ids','meta_key'=>'_nvconsult_user_id','meta_value'=>$uid]);$out=[];foreach($apps as$id){foreach(NVConsult_Core_Document_Requests::items($id)as$r)if($r['status']==='required')$out[]=['id'=>'request-'.$r['id'],'type'=>'action','application_id'=>$id,'title'=>__('Document required','nvconsult-core'),'text'=>ucfirst($r['type']).($r['note']?' — '.$r['note']:''),'time'=>$r['created'],'ts'=>strtotime($r['created'])?:0];$msgs=get_posts(['post_type'=>'nv_message','post_status'=>'private','numberposts'=>20,'meta_query'=>[['key'=>'_nvconsult_application_id','value'=>$id],['key'=>'_nvconsult_sender_role','value'=>'staff']]]);foreach($msgs as$m)if(!get_post_meta($m->ID,'_nvconsult_read_applicant',true))$out[]=['id'=>'message-'.$m->ID,'type'=>'message','application_id'=>$id,'title'=>__('New message','nvconsult-core'),'text'=>wp_trim_words((string)get_post_meta($m->ID,'_nvconsult_message_body',true),18,'…'),'time'=>get_post_time(DATE_ATOM,true,$m),'ts'=>get_post_time('U',true,$m)];$docs=get_posts(['post_type'=>'nv_document','post_status'=>'private','numberposts'=>50,'meta_key'=>'_nvconsult_application_id','meta_value'=>$id]);foreach($docs as$d){$s=(string)get_post_meta($d->ID,'_nvconsult_document_status',true);if(in_array($s,['accepted','rejected','replacement_required'],true))$out[]=['id'=>'document-'.$d->ID.'-'.$s,'type'=>'document','application_id'=>$id,'title'=>__('Document review','nvconsult-core'),'text'=>sprintf('%s — %s',(string)get_post_meta($d->ID,'_nvconsult_original_name',true),ucwords(str_replace('_',' ',$s))),'time'=>get_post_modified_time(DATE_ATOM,true,$d),'ts'=>get_post_modified_time('U',true,$d)];}$history=get_post_meta($id,'_nvconsult_history',false);foreach($history as$k=>$h)if(($h['type']??'')==='status'&&($h['time']??''))$out[]=['id'=>'status-'.$id.'-'.$k,'type'=>'status','application_id'=>$id,'title'=>__('Application update','nvconsult-core'),'text'=>(string)$h['message'],'time'=>(string)$h['time'],'ts'=>strtotime((string)$h['time'])?:0];}usort($out,static fn($a,$b)=>$b['ts']<=>$a['ts']);return array_slice($out,0,100);}
}
