<?php
if (!defined('ABSPATH')) { exit; }
final class NVConsult_Core_Messages {
 public static function init():void{add_action('init',[self::class,'register']);add_action('rest_api_init',[self::class,'routes']);}
 public static function register():void{register_post_type('nv_message',['labels'=>['name'=>__('Messages','nvconsult-core'),'singular_name'=>__('Message','nvconsult-core')],'public'=>false,'show_ui'=>false,'show_in_rest'=>false,'supports'=>[]]);}
 public static function routes():void{register_rest_route('nvconsult/v1','/applications/(?P<id>\d+)/messages',[[ 'methods'=>WP_REST_Server::READABLE,'callback'=>[self::class,'list_messages'],'permission_callback'=>[self::class,'can_access']],[ 'methods'=>WP_REST_Server::CREATABLE,'callback'=>[self::class,'send'],'permission_callback'=>[self::class,'can_access']]]);}
 public static function can_access(WP_REST_Request $r):bool{$id=absint($r['id']);if(!$id||get_post_type($id)!=='nv_application')return false;if(current_user_can('nvconsult_manage_applications'))return true;return is_user_logged_in()&&absint(get_post_meta($id,'_nvconsult_user_id',true))===get_current_user_id();}
 public static function list_messages(WP_REST_Request $r):WP_REST_Response{$id=absint($r['id']);$messages=get_posts(['post_type'=>'nv_message','post_status'=>'private','numberposts'=>100,'orderby'=>'date','order'=>'ASC','meta_key'=>'_nvconsult_application_id','meta_value'=>$id]);$items=array_map(static function($m){$author=absint(get_post_meta($m->ID,'_nvconsult_sender_id',true));$u=$author?get_userdata($author):false;return ['id'=>$m->ID,'body'=>(string)get_post_meta($m->ID,'_nvconsult_message_body',true),'sender'=>$u?$u->display_name:__('NVConsult','nvconsult-core'),'sender_role'=>(string)get_post_meta($m->ID,'_nvconsult_sender_role',true),'created'=>get_post_time(DATE_ATOM,true,$m->ID)];},$messages);return new WP_REST_Response(['items'=>$items],200);}
 public static function send(WP_REST_Request $r){$id=absint($r['id']);$body=sanitize_textarea_field((string)$r->get_param('message'));if($body==='')return new WP_Error('empty_message',__('Message cannot be empty.','nvconsult-core'),['status'=>400]);if(strlen($body)>5000)return new WP_Error('message_too_long',__('Message is too long.','nvconsult-core'),['status'=>400]);$staff=current_user_can('nvconsult_manage_applications');$mid=wp_insert_post(['post_type'=>'nv_message','post_status'=>'private','post_title'=>'Message — Application '.$id],true);if(is_wp_error($mid))return $mid;update_post_meta($mid,'_nvconsult_application_id',$id);update_post_meta($mid,'_nvconsult_sender_id',get_current_user_id());update_post_meta($mid,'_nvconsult_sender_role',$staff?'staff':'applicant');update_post_meta($mid,'_nvconsult_message_body',$body);self::notify($id,$staff,$body);return new WP_REST_Response(['id'=>$mid,'created'=>get_post_time(DATE_ATOM,true,$mid)],201);}
 private static function notify(int $id,bool $staff,string $body):void{if($staff){$email=sanitize_email((string)get_post_meta($id,'_nvconsult_email',true));$subject=__('New message from NVConsult','nvconsult-core');}else{$assigned=absint(get_post_meta($id,'_nvconsult_assigned_user_id',true));$user=$assigned?get_userdata($assigned):false;$email=$user?$user->user_email:get_option('admin_email');$subject=__('New applicant message','nvconsult-core');}if(!$email)return;$preview=wp_trim_words($body,30,'…');wp_mail($email,$subject,sprintf(__('Application #%1$d has a new message:\n\n%2$s','nvconsult-core'),$id,$preview));}
}
