<?php
if(!defined('ABSPATH')){exit;}
final class NVConsult_Core_Followups{
 public static function init():void{add_action('add_meta_boxes_nv_application',[self::class,'box']);add_action('save_post_nv_application',[self::class,'save'],40,2);add_action('nvconsult_daily_followups',[self::class,'run']);add_action('init',[self::class,'schedule']);}
 public static function schedule():void{if(!wp_next_scheduled('nvconsult_daily_followups'))wp_schedule_event(time()+HOUR_IN_SECONDS,'daily','nvconsult_daily_followups');}
 public static function box():void{add_meta_box('nvc-followup',__('Follow-up & Deadline','nvconsult-core'),[self::class,'render'],'nv_application','side','high');}
 public static function render(WP_Post$p):void{wp_nonce_field('nvc_followup','nvc_followup_nonce');$date=(string)get_post_meta($p->ID,'_nvconsult_followup_date',true);$deadline=(string)get_post_meta($p->ID,'_nvconsult_deadline',true);$priority=(string)get_post_meta($p->ID,'_nvconsult_priority',true)?:'normal';echo'<p><label><strong>'.esc_html__('Next follow-up','nvconsult-core').'</strong></label><br><input type="date" name="nvc_followup_date" value="'.esc_attr($date).'" style="width:100%"></p><p><label><strong>'.esc_html__('Case deadline','nvconsult-core').'</strong></label><br><input type="date" name="nvc_deadline" value="'.esc_attr($deadline).'" style="width:100%"></p><p><label><strong>'.esc_html__('Priority','nvconsult-core').'</strong></label><br><select name="nvc_priority" style="width:100%">';foreach(['normal'=>'Normal','high'=>'High','urgent'=>'Urgent']as$v=>$l)printf('<option value="%s" %s>%s</option>',esc_attr($v),selected($priority,$v,false),esc_html($l));echo'</select></p>';}
 public static function save(int$id,WP_Post$p):void{if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(!current_user_can('nvconsult_manage_applications'))return;if(!isset($_POST['nvc_followup_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nvc_followup_nonce'])),'nvc_followup'))return;$changes=[];foreach(['followup_date'=>'Follow-up','deadline'=>'Deadline']as$k=>$label){$old=(string)get_post_meta($id,'_nvconsult_'.$k,true);$v=sanitize_text_field(wp_unslash($_POST['nvc_'.$k]??''));if(!$v||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))$v='';if($old!==$v)$changes[]=sprintf(__('%1$s changed from %2$s to %3$s','nvconsult-core'),$label,$old?:'—',$v?:'—');if($v)update_post_meta($id,'_nvconsult_'.$k,$v);else delete_post_meta($id,'_nvconsult_'.$k);}$oldp=(string)get_post_meta($id,'_nvconsult_priority',true)?:'normal';$priority=sanitize_key($_POST['nvc_priority']??'normal');$priority=in_array($priority,['normal','high','urgent'],true)?$priority:'normal';if($oldp!==$priority)$changes[]=sprintf(__('Priority changed from %1$s to %2$s','nvconsult-core'),ucfirst($oldp),ucfirst($priority));update_post_meta($id,'_nvconsult_priority',$priority);foreach($changes as$text)add_post_meta($id,'_nvconsult_history',['type'=>'case_management','message'=>$text,'time'=>current_time('mysql'),'user_id'=>get_current_user_id()]);}
 public static function run():void{$today=current_time('Y-m-d');$apps=get_posts(['post_type'=>'nv_application','post_status'=>'private','numberposts'=>-1]);foreach($apps as$a){$s=(string)get_post_meta($a->ID,'_nvconsult_status',true);if(in_array($s,['approved','rejected','closed'],true))continue;$follow=(string)get_post_meta($a->ID,'_nvconsult_followup_date',true);$deadline=(string)get_post_meta($a->ID,'_nvconsult_deadline',true);$uid=absint(get_post_meta($a->ID,'_nvconsult_assigned_user_id',true));$u=$uid?get_userdata($uid):false;$email=$u?$u->user_email:get_option('admin_email');if($follow&&$follow<=$today)self::mail_once($a->ID,'followup-'.$today,$email,__('NVConsult follow-up due','nvconsult-core'),sprintf(__('Application #%d is due for follow-up.','nvconsult-core'),$a->ID));if($deadline&&$deadline<$today)self::mail_once($a->ID,'deadline-'.$today,$email,__('NVConsult deadline overdue','nvconsult-core'),sprintf(__('Application #%1$d passed its deadline of %2$s. Immediate review is required.','nvconsult-core'),$a->ID,$deadline));elseif($deadline&&$deadline===date('Y-m-d',strtotime($today.' +1 day')))self::mail_once($a->ID,'deadline-warning-'.$today,$email,__('NVConsult deadline tomorrow','nvconsult-core'),sprintf(__('Application #%1$d has a deadline tomorrow (%2$s).','nvconsult-core'),$a->ID,$deadline));}}
 private static function mail_once(int$id,string$key,string$email,string$subject,string$body):void{if(!$email||get_post_meta($id,'_nvconsult_reminder_'.$key,true))return;if(wp_mail($email,$subject,$body))update_post_meta($id,'_nvconsult_reminder_'.$key,current_time('mysql'));}
 public static function due(int$id):array{$today=current_time('Y-m-d');$f=(string)get_post_meta($id,'_nvconsult_followup_date',true);$d=(string)get_post_meta($id,'_nvconsult_deadline',true);return['followup'=>$f,'deadline'=>$d,'followup_due'=>$f&&$f<=$today,'deadline_overdue'=>$d&&$d<$today,'priority'=>(string)get_post_meta($id,'_nvconsult_priority',true)?:'normal'];}
}
