<?php
if (!defined('ABSPATH')) { exit; }
final class NVConsult_Core_Documents {
 private const TYPES=['passport','cv','photo','academic','experience','language','financial','offer','visa','other']; private const STATES=['uploaded','reviewing','accepted','rejected','replacement_required'];
 public static function init():void{add_action('init',[self::class,'register']);add_action('rest_api_init',[self::class,'routes']);}
 public static function register():void{register_post_type('nv_document',['labels'=>['name'=>__('Documents','nvconsult-core'),'singular_name'=>__('Document','nvconsult-core')],'public'=>false,'show_ui'=>true,'show_in_menu'=>'edit.php?post_type=nv_application','show_in_rest'=>false,'supports'=>['title'],'capability_type'=>'post','map_meta_cap'=>true]);}
 public static function routes():void{register_rest_route('nvconsult/v1','/applications/(?P<id>\d+)/documents',[['methods'=>WP_REST_Server::READABLE,'callback'=>[self::class,'list_docs'],'permission_callback'=>[self::class,'can_access']],['methods'=>WP_REST_Server::CREATABLE,'callback'=>[self::class,'upload'],'permission_callback'=>[self::class,'can_access']]]);}
 public static function can_access(WP_REST_Request$request):bool{$id=absint($request['id']);if(!$id||get_post_type($id)!=='nv_application')return false;if(current_user_can('nvconsult_manage_applications'))return true;return is_user_logged_in()&&absint(get_post_meta($id,'_nvconsult_user_id',true))===get_current_user_id();}
 public static function list_docs(WP_REST_Request$request):WP_REST_Response{$application_id=absint($request['id']);$ids=get_posts(['post_type'=>'nv_document','post_status'=>'private','numberposts'=>-1,'fields'=>'ids','meta_key'=>'_nvconsult_application_id','meta_value'=>$application_id]);$items=array_map(static fn($id)=>['id'=>$id,'type'=>(string)get_post_meta($id,'_nvconsult_document_type',true),'status'=>(string)get_post_meta($id,'_nvconsult_document_status',true),'filename'=>(string)get_post_meta($id,'_nvconsult_original_name',true),'uploaded'=>get_post_time(DATE_ATOM,true,$id)],$ids);return new WP_REST_Response(['items'=>$items],200);}
 public static function upload(WP_REST_Request$request){$application_id=absint($request['id']);$type=sanitize_key((string)$request->get_param('type'));if(!in_array($type,self::TYPES,true))return new WP_Error('invalid_document_type',__('Invalid document type.','nvconsult-core'),['status'=>400]);$files=$request->get_file_params();if(empty($files['file']))return new WP_Error('missing_file',__('A file is required.','nvconsult-core'),['status'=>400]);$file=$files['file'];if(!empty($file['error'])||empty($file['tmp_name'])||!is_uploaded_file($file['tmp_name']))return new WP_Error('upload_failed',__('The upload did not complete successfully.','nvconsult-core'),['status'=>400]);if((int)$file['size']<=0||(int)$file['size']>8*MB_IN_BYTES)return new WP_Error('file_too_large',__('Maximum document size is 8 MB.','nvconsult-core'),['status'=>400]);$mimes=['pdf'=>'application/pdf','jpg|jpeg'=>'image/jpeg','png'=>'image/png'];$check=wp_check_filetype_and_ext($file['tmp_name'],$file['name'],$mimes);if(empty($check['type'])||!in_array($check['type'],array_values($mimes),true))return new WP_Error('invalid_file_type',__('Only PDF, JPG and PNG documents are allowed.','nvconsult-core'),['status'=>400]);require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';$attachment_id=media_handle_sideload(['name'=>sanitize_file_name($file['name']),'tmp_name'=>$file['tmp_name'],'error'=>$file['error'],'size'=>$file['size']],0);if(is_wp_error($attachment_id))return$attachment_id;$doc_id=wp_insert_post(['post_type'=>'nv_document','post_status'=>'private','post_title'=>ucfirst($type).' — Application '.$application_id],true);if(is_wp_error($doc_id)){wp_delete_attachment($attachment_id,true);return$doc_id;}wp_update_post(['ID'=>$attachment_id,'post_parent'=>$doc_id]);update_post_meta($doc_id,'_nvconsult_application_id',$application_id);update_post_meta($doc_id,'_nvconsult_attachment_id',$attachment_id);update_post_meta($doc_id,'_nvconsult_document_type',$type);update_post_meta($doc_id,'_nvconsult_document_status','uploaded');update_post_meta($doc_id,'_nvconsult_original_name',sanitize_file_name($file['name']));add_post_meta($application_id,'_nvconsult_history',['type'=>'document','message'=>sprintf(__('Document uploaded: %s','nvconsult-core'),ucfirst($type)),'time'=>current_time('mysql'),'user_id'=>get_current_user_id()]);return new WP_REST_Response(['document_id'=>$doc_id,'type'=>$type,'status'=>'uploaded'],201);}
}
