<?php
if(!defined('ABSPATH')){exit;}
final class NVConsult_Core_Security{
 public static function init():void{add_filter('rest_pre_dispatch',[self::class,'rate_limit'],10,3);add_action('admin_init',[self::class,'security_headers']);add_filter('wp_privacy_personal_data_erasers',[self::class,'eraser']);}
 public static function security_headers():void{if(headers_sent())return;header('X-Content-Type-Options: nosniff');header('Referrer-Policy: strict-origin-when-cross-origin');header('Permissions-Policy: camera=(), microphone=(), geolocation=()');}
 public static function rate_limit($result,WP_REST_Server$server,WP_REST_Request$request){if(strpos($request->get_route(),'/nvconsult/v1/')!==0)return$result;$uid=get_current_user_id();$key='nvc_rl_'.md5(($uid?:($_SERVER['REMOTE_ADDR']??'guest')).gmdate('YmdHi'));$n=(int)get_transient($key);if($n>=120)return new WP_Error('nvc_rate_limit',__('Too many requests. Please retry shortly.','nvconsult-core'),['status'=>429]);set_transient($key,$n+1,2*MINUTE_IN_SECONDS);return$result;}
 public static function eraser(array$e):array{$e['nvconsult-core']=['eraser_friendly_name'=>__('NVConsult applicant data','nvconsult-core'),'callback'=>[self::class,'erase']];return$e;}
 public static function erase(string$email,int$page=1):array{$user=get_user_by('email',$email);if(!$user)return['items_removed'=>false,'items_retained'=>false,'messages'=>[], 'done'=>true];$apps=get_posts(['post_type'=>'nv_application','post_status'=>'any','numberposts'=>100,'meta_key'=>'_nvconsult_user_id','meta_value'=>$user->ID]);$removed=false;foreach($apps as$a){foreach(['_nvconsult_applicant_name','_nvconsult_phone','_nvconsult_passport','_nvconsult_address']as$k)if(metadata_exists('post',$a->ID,$k)){delete_post_meta($a->ID,$k);$removed=true;}}return['items_removed'=>$removed,'items_retained'=>true,'messages'=>[__('Application records may be retained where legally or contractually required; direct identifiers were removed where supported.','nvconsult-core')],'done'=>true];}
}
